version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester-uv
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            uv venv --python 3.12 /usr/local/share/virtualenvs/tap-campaign-monitor
            source /usr/local/share/virtualenvs/tap-campaign-monitor/bin/activate
            uv pip install "pip==24.0" "setuptools==70.0.0"
            uv pip install .[dev]
      - run:
          name: 'JSON Validator'
          command: |
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            stitch-validate-json /usr/local/share/virtualenvs/tap-campaign-monitor/lib/python3.12/site-packages/tap_campaign_monitor/schemas/*.json
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-campaign-monitor/bin/activate
            pylint tap_campaign_monitor  -d C,R,W
      - run:
          name: "Unit Tests"
          command: |
            source /usr/local/share/virtualenvs/tap-campaign-monitor/bin/activate
            uv pip install pytest coverage
            mkdir -p test_output
            coverage run -m pytest tests/unittests --junitxml=test_output/report.xml
            coverage report
            coverage html
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: htmlcov
      - run:
          name: "Integration Tests"
          command: |
            source /usr/local/share/virtualenvs/tap-campaign-monitor/bin/activate
            uv pip install --upgrade awscli
            aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/tap_tester_sandbox dev_env.sh
            source dev_env.sh
            unset USE_STITCH_BACKEND
            run-test --tap=tap-campaign-monitor tests            
            stitch-validate-json /usr/local/share/virtualenvs/tap-campaign-monitor/lib/python3.9/site-packages/tap_campaign_monitor/schemas/*.json         
workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
  build_daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: circleci-user
